export const metadata = {
    title: "Next.js",
    description: "This was generated by NextJs"
}

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    )
}
